version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

  app:
    build: ./app
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://rootuser:rootpass@mongodb:27017
    volumes:
      - ./app:/usr/src/app

volumes:
  mongodb_data_container:
